#!/usr/bin/env bash

if [ "BROWSER" != "$1" ]
then
    exec $0 BROWSER &
    ( cd `dirname $0` && exec java -Dconfig.file="`pwd`/application.conf" $@ -cp "`pwd`/lib/*" play.core.server.NettyServer "`pwd`" )
else
    echo "Starting browser in 10 seconds..."
    sleep 10
    if [ "`uname -s`" == "Darwin" ]
    then
        open "http://localhost:9000/"
    else
        xdg-open "http://localhost:9000/"
    fi
fi

