#!/usr/bin/env bash

echo "Starting browser..."
if [ "`uname -s`" == "Darwin" ]
then
    open "startui/start.html"
else
    xdg-open "startui/start.html"
fi

echo "Starting Web UI..."
( cd "`dirname "$0"`" && exec java -Dconfig.file="`pwd`/application.conf" $@ -cp "`pwd`/lib/*" play.core.server.NettyServer "`pwd`" )
